name: Test

on:
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hello There!'
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: npm install
      - name: Test utils
        run: npm test utils
  test-integration:
    needs: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4.1.1
      - name: Install dependencies 
        run: npm install
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: test_db 
          postgresql user: test_user 
          postgresql password: password
      - name: Test app
        run: PGDATABASE=nc_news_test PGUSER=test_user PGPASSWORD=password npm run test-app
